module.exports={
    ENV_IS_SUB:'YURI2WEB_ENV_IS_SUB'  ,
    ENV_WORKER_ID:'YURI2WEB_ENV_WORKER_ID'  ,
    TYPE_MSG_LISTEN:'YURI2WEB_TYPE_MSG_LISTEN',
    TYPE_MSG_EVAL:'YURI2WEB_TYPE_MSG_EVAL',
    TYPE_MSG_EVAL_REL:'YURI2WEB_TYPE_MSG_EVA_REL',
    TYPE_MSG_HANDLE_BACKUP:'YURI2WEB_TYPE_MSG_HANDLE_BACKUP',
    TYPE_MSG_HANDLE_BACKUP_REL:'YURI2WEB_TYPE_MSG_HANDLE_BACKUP_REL',
};